language: node_js

node_js:
  - "7.9.0"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
